/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BetterflowAssets;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::AssetImage IconRock;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::AssetImage IconPaper;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::AssetImage LabelRock;
extern const Sifteo::AssetImage IconScissors;
extern const Sifteo::AssetImage Tip1;
extern const Sifteo::AssetImage Tip2;
extern const Sifteo::AssetImage LabelScissors;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::AssetImage LabelPaper;
